#!/usr/bin/env python3
"""Lint docs/ for broken intra-doc Markdown links.

Scans every ``docs/**/*.md`` file, extracts inline links of the form
``[text](target)`` and verifies that:

* If the link is relative (no ``http://`` / ``https://`` / ``mailto:`` /
  protocol-relative ``//`` prefix), the resolved file exists under ``docs/``.
* If the link contains a fragment ``#anchor``, the anchor matches one of:
    - an explicit ``{#anchor}`` attribute attached to a heading or paragraph,
    - or a heading slug (H1-H4) generated by the same simple slugifier MkDocs
      uses by default (toc.slugify with ``slugify_kwargs={'separator':'-'}``)
      approximated as: lowercase, non-alphanumeric runs collapsed to ``-``.

Pure-fragment links (``#anchor``) are resolved against the current page.

External URLs, ``mailto:``, in-page-only anchors that match are skipped from
the failure list. The script reports remaining broken links.

Usage:
    python meta/scripts/check_broken_links.py            # human report
    python meta/scripts/check_broken_links.py --check    # CI mode (informational)

Exit codes:
    0  always (informational mode)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from urllib.parse import unquote

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"

# Match inline [text](target) links. text may contain nested brackets via
# escapes, but we keep it simple — markdown rendered by mkdocs has the same
# limitation in practice. Skip image links ``![alt](url)``.
LINK_RE = re.compile(r"(?<!\!)\[(?P<text>[^\]\n]*)\]\((?P<target>[^)\s]+)(?:\s+\"[^\"]*\")?\)")
EXPLICIT_ANCHOR_RE = re.compile(r"\{#([A-Za-z0-9_\-:.]+)\}")
HEADING_RE = re.compile(r"^(#{1,4})\s+(.+?)\s*$", re.MULTILINE)
PROTOCOL_RE = re.compile(r"^(?:[a-zA-Z][a-zA-Z0-9+.\-]*:|//)")


def slugify(text: str, separator: str = "-") -> str:
    """Match python-markdown ``toc.slugify`` (the default mkdocs uses).

    1. Strip ``{#explicit}`` attribute lists.
    2. Strip inline-code/emphasis markers (these are removed by markdown
       before slugification).
    3. NFKD-normalize and ASCII-encode (non-ASCII chars are dropped).
    4. Remove anything that isn't word-char, space, or hyphen.
    5. Lowercase, then collapse runs of whitespace/separator to one separator.
    """
    import unicodedata
    text = EXPLICIT_ANCHOR_RE.sub("", text)
    # Strip markdown inline code and emphasis markers
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"[*_]", "", text)
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = re.sub(r"[^\w\s-]", "", text).strip().lower()
    return re.sub(rf"[{re.escape(separator)}\s]+", separator, text)


def collect_anchors(md_text: str) -> set[str]:
    anchors: set[str] = set()
    for m in EXPLICIT_ANCHOR_RE.finditer(md_text):
        anchors.add(m.group(1))
    for m in HEADING_RE.finditer(md_text):
        anchors.add(slugify(m.group(2)))
    return anchors


def strip_code_blocks(md_text: str) -> str:
    """Remove fenced code blocks so links inside code don't trigger checks."""
    out: list[str] = []
    in_fence = False
    fence_marker = ""
    for line in md_text.splitlines():
        stripped = line.lstrip()
        if not in_fence and (stripped.startswith("```") or stripped.startswith("~~~")):
            in_fence = True
            fence_marker = stripped[:3]
            continue
        if in_fence and stripped.startswith(fence_marker):
            in_fence = False
            continue
        if in_fence:
            continue
        out.append(line)
    # Also strip inline code spans `...` to avoid false positives
    text = "\n".join(out)
    text = re.sub(r"`[^`\n]*`", "", text)
    return text


def resolve_target(src: Path, target: str) -> tuple[Path | None, str | None]:
    """Resolve a relative link target.

    Returns (path_or_none, anchor_or_none). ``path_or_none`` is None for
    pure-fragment links (anchor refers to current page).
    """
    target = unquote(target)
    if "#" in target:
        path_part, _, anchor = target.partition("#")
    else:
        path_part, anchor = target, ""

    if path_part == "":
        return None, anchor or None

    # Resolve relative to source file's directory
    base = src.parent
    resolved = (base / path_part).resolve()

    # If target points to a directory, mkdocs serves the index.md
    if resolved.is_dir():
        idx = resolved / "index.md"
        if idx.exists():
            resolved = idx

    return resolved, anchor or None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="CI mode (informational, always exit 0)")
    parser.add_argument("--strict", action="store_true", help="Exit 1 if any broken link found")
    args = parser.parse_args()

    md_files = sorted(DOCS_DIR.rglob("*.md"))
    # Pre-load anchors for every page
    page_anchors: dict[Path, set[str]] = {}
    page_text: dict[Path, str] = {}
    for f in md_files:
        try:
            text = f.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            text = ""
        page_text[f] = text
        page_anchors[f] = collect_anchors(text)

    broken: list[tuple[Path, str, str]] = []  # (src, target, reason)

    for src in md_files:
        text = strip_code_blocks(page_text[src])
        for m in LINK_RE.finditer(text):
            target = m.group("target")
            # Skip absolute URLs, protocol-relative, mailto:, tel:, etc.
            if PROTOCOL_RE.match(target):
                continue
            # Skip absolute site paths (start with /) — those are mkdocs root
            # references which mkdocs --strict handles separately.
            if target.startswith("/"):
                continue
            resolved, anchor = resolve_target(src, target)

            if resolved is None:
                # pure fragment — check against current page
                if anchor and anchor not in page_anchors[src]:
                    broken.append((src, target, f"anchor #{anchor} not found in self"))
                continue

            if not resolved.exists():
                broken.append((src, target, f"file not found: {resolved.relative_to(REPO_ROOT) if REPO_ROOT in resolved.parents else resolved}"))
                continue

            if anchor:
                if resolved.suffix != ".md":
                    # not a markdown target — skip anchor check
                    continue
                anchors = page_anchors.get(resolved)
                if anchors is None:
                    try:
                        anchors = collect_anchors(resolved.read_text(encoding="utf-8"))
                    except (OSError, UnicodeDecodeError):
                        anchors = set()
                    page_anchors[resolved] = anchors
                if anchor not in anchors:
                    rel = resolved.relative_to(DOCS_DIR)
                    broken.append((src, target, f"anchor #{anchor} not found in {rel}"))

    # Report
    if not broken:
        print("check_broken_links: OK (no broken links)")
        return 0

    # Group by source file
    by_src: dict[Path, list[tuple[str, str]]] = {}
    for src, tgt, reason in broken:
        by_src.setdefault(src, []).append((tgt, reason))

    print(f"check_broken_links: found {len(broken)} broken link(s) in {len(by_src)} file(s)\n")
    for src in sorted(by_src):
        rel = src.relative_to(REPO_ROOT)
        print(f"  {rel}")
        for tgt, reason in by_src[src]:
            print(f"    - [{tgt}]  ({reason})")

    if args.check:
        sys.stderr.write(f"check_broken_links: {len(broken)} broken link(s) (informational)\n")
        return 0

    if args.strict:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
