#!/usr/bin/env python3
"""Inject glossary links into docs/**/*.md.

For every term defined in ``docs/reference/glossary.md`` (i.e. lines of the
form ``### <Term> {#term-<slug>}``), find the **first occurrence** of the term
in each other Markdown page's body and replace it with a Markdown link to the
glossary anchor.  All later occurrences on the same page are left untouched.

The injection is conservative:

* Frontmatter, code blocks (fenced and indented), and HTML comments are skipped.
* ATX/Setext headings are skipped.
* Lines inside already-rendered evidence blocks (``<!-- evidence-rendered:start
  -->`` ... ``<!-- evidence-rendered:end -->``) are skipped.
* Existing Markdown links / link text are skipped (we never inject inside a
  ``[...](...)`` construct).
* Terms that look "too generic" (very short Japanese strings or common
  katakana noise words) are excluded via ``STOPLIST``.  Short ASCII acronyms
  (BGP, ACL, RIB, ...) are explicitly allowed via ``ALLOW_SHORT``.

Idempotency: every touched file gets a trailing comment
``<!-- glossary-links-injected: <sha1> -->`` whose payload is the sha1 of the
sorted list of (term, anchor) pairs that were injected.  Re-running with the
same glossary contents is a no-op.

Modes
-----
default   Rewrite drifted files in place. Print summary. Exit 0.
--check   Report drift only. Exit 1 if any file would change.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
GLOSSARY = DOCS / "reference" / "glossary.md"
MARKER_PREFIX = "<!-- glossary-links-injected:"
MARKER_RE = re.compile(r"<!-- glossary-links-injected: ([0-9a-f]+) -->")

HEADING_RE = re.compile(r"^(###\s+)(.+?)(\s*\{#(term-[A-Za-z0-9._-]+)\})\s*$")

# Words to exclude even though they appear as glossary terms.  These are too
# generic in running Japanese text and would create excessive noise links.
# (Currently the glossary has no entries that match these strings, but the
# list is here as a guardrail for future additions.)
STOPLIST: set[str] = {
    "ルーティング",
    "インタフェース",
    "インターフェース",
    "設定",
    "ポート",
    "リンク",
    "イベント",
    "メッセージ",
    "テーブル",
    "プロトコル",
}

# Short (<= 3 char) ASCII terms are normally too ambiguous to auto-link, so we
# require an explicit allow-list.  Anything not listed here that is <= 3 chars
# (e.g. "VS") is skipped.
ALLOW_SHORT: set[str] = {
    "AAA", "ACL", "AQM", "ARP", "BFD", "BGP", "CRM", "DPB", "DPU",
    "ECN", "ENI", "ETS", "FDB", "FPM", "FRR", "GCU", "HLD", "IFA",
    "INT", "LAG", "MMU", "MPLS", "MUX", "NAT", "NDP", "NPU", "PFC",
    "QoS", "RIF", "SAI", "TAM", "ToS", "VRF", "VOQ", "VS",
    "WRED", "WRR", "ZTP",
}


def parse_frontmatter(text: str) -> tuple[str, str]:
    m = re.match(r"^(---\s*\n.*?\n---\s*\n)", text, re.DOTALL)
    if not m:
        return "", text
    return m.group(1), text[m.end():]


def collect_terms() -> list[tuple[str, str]]:
    """Return [(term, anchor)] in document order, deduped."""
    text = GLOSSARY.read_text(encoding="utf-8")
    _fm, body = parse_frontmatter(text)
    seen: set[str] = set()
    out: list[tuple[str, str]] = []
    for line in body.splitlines():
        m = HEADING_RE.match(line)
        if not m:
            continue
        term = m.group(2).strip()
        anchor = m.group(4)
        # Skip composite-name entries like "natmgrd / natsyncd": they would
        # never match verbatim in prose.  Pick the first component instead.
        if " / " in term:
            term = term.split(" / ", 1)[0].strip()
        if term in seen:
            continue
        if term in STOPLIST:
            continue
        # Length / character-set filters.
        ascii_only = all(ord(c) < 128 for c in term)
        if ascii_only and len(term) <= 3 and term not in ALLOW_SHORT:
            continue
        if len(term) < 2:
            continue
        seen.add(term)
        out.append((term, anchor))
    # Sort longer terms first so e.g. "EVPN-MH" is preferred over "EVPN" when
    # both could match the same text starting position.
    out.sort(key=lambda x: (-len(x[0]), x[0]))
    return out


# ---------------------------------------------------------------------------
# Per-file processing
# ---------------------------------------------------------------------------

FENCE_RE = re.compile(r"^(\s*)(```|~~~)")
EVIDENCE_OPEN = "<!-- evidence-rendered:start -->"
EVIDENCE_CLOSE = "<!-- evidence-rendered:end -->"
HTML_COMMENT_OPEN_RE = re.compile(r"<!--")
HTML_COMMENT_CLOSE_RE = re.compile(r"-->")

# Auto-managed region markers: content between BEGIN/END is regenerated by
# other scripts (gen_next_reads, inject_yang_sibling, inject_yang_xref,
# inject_cli_sibling, enrich_chapter_index_related). Injecting glossary links
# into these regions creates an idempotency cycle: the next regenerator run
# strips the anchors and inject_glossary_links re-adds them on the next pass.
# Skip them entirely.
AUTO_REGIONS: tuple[tuple[str, str], ...] = (
    ("<!-- next-reads -->", "<!-- /next-reads -->"),
    ("<!-- yang-sibling -->", "<!-- /yang-sibling -->"),
    ("<!-- yang-xref -->", "<!-- /yang-xref -->"),
    ("<!-- cli-sibling -->", "<!-- /cli-sibling -->"),
    ("<!-- chapter-index-related -->", "<!-- /chapter-index-related -->"),
)


def rel_glossary_link(page_rel: str, anchor: str) -> str:
    """Return relative path from `docs/<page_rel>` to glossary, with anchor."""
    page = Path(page_rel)
    # Depth of the page from docs/ (number of parent directories).
    depth = len(page.parts) - 1
    if depth == 0:
        prefix = "./"
    else:
        prefix = "../" * depth
    return f"{prefix}reference/glossary.md#{anchor}"


def _line_is_eligible(line: str) -> bool:
    """Cheap pre-filter: a line that is a heading / blockquote-only / blank
    cannot host an injection."""
    stripped = line.lstrip()
    if not stripped:
        return False
    if stripped.startswith("#"):
        return False
    if stripped.startswith("<!--"):
        return False
    # Lines that are just an admonition declaration (``??? note "..."``).
    if stripped.startswith("???") or stripped.startswith("!!!"):
        return False
    return True


def _mask_protected_spans(line: str) -> list[tuple[int, int]]:
    """Return list of (start, end) char ranges within ``line`` where injection
    is forbidden: existing markdown links, inline code, and raw HTML tags."""
    spans: list[tuple[int, int]] = []
    # Inline code: `...` (non-greedy, single line).
    for m in re.finditer(r"`[^`]+`", line):
        spans.append((m.start(), m.end()))
    # Markdown links: [text](target) and ![alt](target).
    for m in re.finditer(r"!?\[[^\]]*\]\([^)]*\)", line):
        spans.append((m.start(), m.end()))
    # Reference-style links: [text][ref].
    for m in re.finditer(r"\[[^\]]+\]\[[^\]]*\]", line):
        spans.append((m.start(), m.end()))
    # Footnote references and definitions: [^key] and [^key]:.
    # Injecting inside a footnote key turns ``[^fpmsyncd]`` into the broken
    # ``[^[fpmsyncd](...)]`` form which never resolves to its definition.
    for m in re.finditer(r"\[\^[^\]\s]+\]", line):
        spans.append((m.start(), m.end()))
    # Raw HTML tags.
    for m in re.finditer(r"<[^>]+>", line):
        spans.append((m.start(), m.end()))
    return spans


def _in_span(pos: int, end: int, spans: list[tuple[int, int]]) -> bool:
    for s, e in spans:
        if pos < e and end > s:
            return True
    return False


def _count_term_occurrences(
    lines: list[str],
    eligible: list[bool],
    term: str,
) -> int:
    """Count occurrences of ``term`` across eligible lines, outside protected
    spans. Word-boundary aware for ASCII-only terms (mirrors injection logic)."""
    ascii_only = all(ord(c) < 128 for c in term)

    def _wordy(ch: str) -> bool:
        return ch.isalnum() or ch == "_"

    total = 0
    for idx, line in enumerate(lines):
        if not eligible[idx]:
            continue
        spans = _mask_protected_spans(line)
        search_from = 0
        while True:
            p = line.find(term, search_from)
            if p < 0:
                break
            end = p + len(term)
            if _in_span(p, end, spans):
                search_from = p + 1
                continue
            if ascii_only:
                before = line[p - 1] if p > 0 else ""
                after = line[end] if end < len(line) else ""
                if (before and _wordy(before)) or (after and _wordy(after)):
                    search_from = p + 1
                    continue
            total += 1
            search_from = end
    return total


def _demote_existing_links(
    lines: list[str],
    terms_to_demote: set[tuple[str, str]],
) -> tuple[list[str], int]:
    """Replace ``[term](.../glossary.md#anchor)`` with bare ``term`` for the
    given (term, anchor) pairs. Returns (new_lines, demote_count)."""
    if not terms_to_demote:
        return lines, 0
    demote_count = 0
    new_lines = list(lines)
    for term, anchor in terms_to_demote:
        pat = re.compile(
            r"\[(" + re.escape(term) + r")\]\([^)]*#" + re.escape(anchor) + r"\)"
        )
        for idx, line in enumerate(new_lines):
            new_line, n = pat.subn(r"\1", line)
            if n:
                new_lines[idx] = new_line
                demote_count += n
    return new_lines, demote_count


# Per-page hard cap on total glossary links (safety: prevents pathological
# pages from getting hundreds of injections).
PAGE_CAP_DEFAULT = 30
PAGE_CAP_REFERENCE = 30

# For Reference-area pages, after the first-occurrence pass, allow up to
# ``BOOST_PER_TERM`` *additional* occurrences of each already-linked term to
# improve glossary density (audit-21 finding: many CLI / YANG / Runbook pages
# only had 1 link). Capped by ``PAGE_CAP_REFERENCE``.
BOOST_PER_TERM = 2
REFERENCE_BOOST_PREFIXES = (
    "reference/cli/",
    "reference/yang/",
    "reference/runbooks/",
    "reference/config-db/",
)


def process_file(
    path: Path,
    terms: list[tuple[str, str]],
    min_occurrences: int = 1,
    demote_below_threshold: bool = False,
) -> tuple[str, int, list[tuple[str, str]]]:
    """Return (new_text, injected_count, injected_pairs).

    ``min_occurrences``: only inject a link for a term if it appears at least
    this many times on eligible lines in the page (default 1 = legacy
    behavior).
    ``demote_below_threshold``: if True, also un-link any pre-existing
    glossary link for terms that fail the threshold on this page.
    """
    original = path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(original)
    rel = path.relative_to(DOCS).as_posix()
    is_reference_boost = rel.startswith(REFERENCE_BOOST_PREFIXES)
    page_cap = PAGE_CAP_REFERENCE if is_reference_boost else PAGE_CAP_DEFAULT

    # Strip any pre-existing marker line so we can recompute it.
    # Strip ALL pre-existing marker lines (anywhere in body, not just at end).
    # Earlier versions anchored the strip to ``$`` only, so if another generator
    # appended content after the marker, a later inject run emitted a *second*
    # marker at the new tail. We now remove every marker and recompute one.
    body_stripped = re.sub(
        r"\n*<!-- glossary-links-injected: [0-9a-f]+ -->[ \t]*\n?",
        "\n",
        body,
    )
    body_stripped = re.sub(r"\n{3,}$", "\n\n", body_stripped)

    lines = body_stripped.splitlines()

    # Pre-compute per-line state: in-fence, in-evidence-rendered, in-html-comment.
    in_fence = False
    fence_marker = ""
    in_evidence = False
    in_html_comment = False
    in_auto_region = False
    auto_close = ""
    eligible: list[bool] = []
    for line in lines:
        line_eligible = True
        # Auto-managed region tracking (yang-sibling / yang-xref / next-reads /
        # cli-sibling / chapter-index-related). Anything between BEGIN/END is
        # owned by the regenerator and must not be touched here.
        if in_auto_region:
            line_eligible = False
            if auto_close in line:
                in_auto_region = False
                auto_close = ""
        else:
            for open_m, close_m in AUTO_REGIONS:
                if open_m in line:
                    in_auto_region = True
                    auto_close = close_m
                    line_eligible = False
                    break
        m = FENCE_RE.match(line)
        if m:
            marker = m.group(2)
            if not in_fence:
                in_fence = True
                fence_marker = marker
                line_eligible = False
            elif fence_marker == marker:
                in_fence = False
                line_eligible = False
            else:
                line_eligible = False
        elif in_fence:
            line_eligible = False
        # Indented code block (4-space indent on otherwise blank line section)
        # is hard to detect without state; approximate by treating any line
        # starting with 4 spaces or a tab that is *not* a list continuation as
        # code.  Safer to just skip.
        if line_eligible and (line.startswith("    ") or line.startswith("\t")):
            # Heuristic: if the line is part of an admonition body (preceded by
            # an admonition declaration) we still skip it -- this conveniently
            # excludes the rendered evidence excerpt blocks.
            line_eligible = False

        if EVIDENCE_OPEN in line:
            in_evidence = True
            line_eligible = False
        if in_evidence:
            line_eligible = False
        if EVIDENCE_CLOSE in line:
            in_evidence = False
            line_eligible = False

        # HTML comment tracking (multi-line).
        if in_html_comment:
            line_eligible = False
            if HTML_COMMENT_CLOSE_RE.search(line):
                in_html_comment = False
        else:
            opens = len(HTML_COMMENT_OPEN_RE.findall(line))
            closes = len(HTML_COMMENT_CLOSE_RE.findall(line))
            if opens > closes:
                in_html_comment = True
                line_eligible = False
            elif opens > 0 and opens == closes:
                # Self-contained comment line: still skip.
                line_eligible = False

        if line_eligible and not _line_is_eligible(line):
            line_eligible = False

        eligible.append(line_eligible)

    # First-occurrence injection per term.
    remaining = {term: anchor for term, anchor in terms}

    # If a term is *already* linked to its glossary anchor anywhere in the
    # body, suppress further injection for that term (idempotency: a previous
    # run already handled it; do not chase later occurrences).
    full_body = "\n".join(lines)
    already_linked: set[tuple[str, str]] = set()
    for term, anchor in list(remaining.items()):
        # Match [<term>](...#<anchor>) loosely.
        pat = re.compile(
            r"\[" + re.escape(term) + r"\]\([^)]*#" + re.escape(anchor) + r"\)"
        )
        if pat.search(full_body):
            already_linked.add((term, anchor))
            del remaining[term]

    # Apply min-occurrences threshold: drop candidates that appear fewer than
    # ``min_occurrences`` times on eligible lines.
    if min_occurrences > 1:
        for term in list(remaining.keys()):
            if _count_term_occurrences(lines, eligible, term) < min_occurrences:
                del remaining[term]

    new_lines = list(lines)

    # Optional: demote already-linked terms whose occurrence count (including
    # the linked one, which is in a protected span and therefore NOT counted
    # by _count_term_occurrences) is below the threshold. We un-link and then
    # re-count plain occurrences; if still under threshold, leave un-linked.
    demote_count = 0
    if demote_below_threshold and min_occurrences > 1 and already_linked:
        to_check: set[tuple[str, str]] = set()
        for term, anchor in already_linked:
            # Build temp un-linked view to count true occurrences.
            tmp_lines, _ = _demote_existing_links(new_lines, {(term, anchor)})
            occ = _count_term_occurrences(tmp_lines, eligible, term)
            if occ < min_occurrences:
                to_check.add((term, anchor))
        new_lines, demote_count = _demote_existing_links(new_lines, to_check)

    injected_pairs: list[tuple[str, str]] = []
    injected_count = 0

    # Iterate lines, then terms; we want the *earliest* occurrence per term,
    # so scan line-by-line and at each line try every remaining term.
    for idx, line in enumerate(new_lines):
        if not eligible[idx]:
            continue
        if injected_count >= page_cap:
            break
        if not remaining:
            break
        # Recompute protected spans lazily.
        spans = _mask_protected_spans(line)
        # Try terms in order longest-first to avoid nested substring conflicts.
        for term in sorted(remaining.keys(), key=lambda t: (-len(t), t)):
            anchor = remaining[term]
            # Find earliest occurrence not in a protected span.
            search_from = 0
            found_pos = -1
            while True:
                p = line.find(term, search_from)
                if p < 0:
                    break
                if not _in_span(p, p + len(term), spans):
                    found_pos = p
                    break
                search_from = p + 1
            if found_pos < 0:
                continue
            # Word-boundary heuristic for ASCII-only terms to avoid linking
            # inside identifiers like "BGPSESSION" or "ACL_TABLE".
            ascii_only = all(ord(c) < 128 for c in term)
            if ascii_only:
                before = line[found_pos - 1] if found_pos > 0 else ""
                after_idx = found_pos + len(term)
                after = line[after_idx] if after_idx < len(line) else ""
                def _wordy(ch: str) -> bool:
                    return ch.isalnum() or ch == "_"
                if (before and _wordy(before)) or (after and _wordy(after)):
                    continue
            link = f"[{term}]({rel_glossary_link(rel, anchor)})"
            line = line[:found_pos] + link + line[found_pos + len(term):]
            new_lines[idx] = line
            # Refresh protected spans after mutation.
            spans = _mask_protected_spans(line)
            injected_pairs.append((term, anchor))
            injected_count += 1
            del remaining[term]
            if not remaining:
                break
            if injected_count >= page_cap:
                break

    # ---- Reference-area boost pass: link up to BOOST_PER_TERM additional
    # occurrences of each already-linked term, to raise glossary density on
    # CLI / YANG / Runbook / CONFIG_DB reference pages.
    boost_added = 0
    if is_reference_boost and injected_count < page_cap:
        # Build (term, anchor) list of terms linked on this page: from this
        # run's first pass plus from prior runs (re-detected in current text).
        linked_terms: dict[str, str] = {t: a for t, a in injected_pairs}
        scan_text = "\n".join(new_lines)
        for term, anchor in terms:
            if term in linked_terms:
                continue
            pat = re.compile(
                r"\[" + re.escape(term) + r"\]\([^)]*#" + re.escape(anchor) + r"\)"
            )
            if pat.search(scan_text):
                linked_terms[term] = anchor

        # Only boost ASCII-only "tech" terms (CONFIG_DB, orchagent, BGP, ...).
        # Skip Japanese / kana terms where multi-link noise is undesirable.
        boost_targets = [
            (t, a) for t, a in linked_terms.items()
            if all(ord(c) < 128 for c in t)
        ]
        # Longer first to avoid nested matches.
        boost_targets.sort(key=lambda x: (-len(x[0]), x[0]))

        for term, anchor in boost_targets:
            if injected_count >= page_cap:
                break
            link = f"[{term}]({rel_glossary_link(rel, anchor)})"
            # Count existing occurrences of this exact link in current body so
            # re-runs converge: stop once we have 1 (first-pass) + BOOST_PER_TERM.
            existing = sum(line.count(link) for line in new_lines)
            already_extra = max(0, existing - 1)
            added = already_extra
            for idx, line in enumerate(new_lines):
                if added >= BOOST_PER_TERM:
                    break
                if injected_count >= page_cap:
                    break
                if not eligible[idx]:
                    continue
                spans = _mask_protected_spans(line)
                search_from = 0
                while added < BOOST_PER_TERM and injected_count < page_cap:
                    p = line.find(term, search_from)
                    if p < 0:
                        break
                    end = p + len(term)
                    if _in_span(p, end, spans):
                        search_from = p + 1
                        continue
                    before = line[p - 1] if p > 0 else ""
                    after = line[end] if end < len(line) else ""
                    if (before and (before.isalnum() or before == "_")) or \
                       (after and (after.isalnum() or after == "_")):
                        search_from = p + 1
                        continue
                    line = line[:p] + link + line[end:]
                    new_lines[idx] = line
                    spans = _mask_protected_spans(line)
                    injected_pairs.append((term, anchor))
                    injected_count += 1
                    added += 1
                    boost_added += 1
                    search_from = p + len(link)

    # Count marker occurrences in the ORIGINAL body. If >1, the file is in
    # duplicate-marker drift state (from an older non-idempotent run) and must
    # be rewritten even when this pass had no new injections.
    orig_marker_count = len(MARKER_RE.findall(body))

    if injected_count == 0 and demote_count == 0 and orig_marker_count <= 1:
        # No new injections, no demotions, no duplicate-marker cleanup needed.
        # Preserve existing file content verbatim so a re-run is a true no-op.
        return original, 0, []

    if injected_count > 0:
        payload = ",".join(f"{t}:{a}" for t, a in sorted(injected_pairs))
        digest = hashlib.sha1(payload.encode("utf-8")).hexdigest()[:12]
        marker = f"<!-- glossary-links-injected: {digest} -->"
        new_body = "\n".join(new_lines).rstrip() + "\n\n" + marker + "\n"
    else:
        # Demotion-only path: keep / recompute marker if present, otherwise
        # just rewrite the body without a fresh marker.
        existing_marker_m = MARKER_RE.search(body)
        suffix = ""
        if existing_marker_m:
            suffix = "\n\n" + existing_marker_m.group(0) + "\n"
        else:
            suffix = "\n"
        new_body = "\n".join(new_lines).rstrip() + suffix
    return fm + new_body, injected_count, injected_pairs


def iter_target_files() -> list[Path]:
    # Auto-generated pages (rewritten by other meta/scripts/gen_*.py jobs).
    # Their content is reproduced from source pages with original-depth
    # relative links, so any glossary links we inject here would be either
    # wiped on next regeneration or end up with the wrong relative depth.
    SKIP_EXACT = {
        "reference/glossary.md",
        "reference/verification/discrepancy-index.md",
        "reference/verification/stale-verified.md",
        "_meta/coverage.md",
        "_meta/changelog.md",
        "_meta/discrepancies.md",
        "_meta/sitemap.md",
        "_meta/snapshot.md",
    }
    out: list[Path] = []
    for p in sorted(DOCS.rglob("*.md")):
        rel = p.relative_to(DOCS).as_posix()
        if rel in SKIP_EXACT:
            continue
        if rel.startswith("reference/glossary/"):
            continue
        out.append(p)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if drift")
    ap.add_argument(
        "--verbose", "-v", action="store_true", help="print per-file injection counts"
    )
    ap.add_argument(
        "--min-occurrences",
        type=int,
        default=1,
        help=(
            "Only inject a glossary link for a term if it appears at least "
            "N times on the page (default: 1, i.e. legacy first-hit behavior)"
        ),
    )
    ap.add_argument(
        "--demote-below-threshold",
        action="store_true",
        help=(
            "Also un-link any pre-existing glossary link for terms that fail "
            "the --min-occurrences threshold on the page"
        ),
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Compute changes and print summary without writing files",
    )
    ap.add_argument(
        "--report",
        type=str,
        default=None,
        help="Write a per-file dry-run report (markdown) to this path",
    )
    args = ap.parse_args()

    if args.min_occurrences < 1:
        print("error: --min-occurrences must be >= 1", file=sys.stderr)
        return 2

    terms = collect_terms()
    if not terms:
        print("warning: no glossary terms collected", file=sys.stderr)
        return 0

    total_files = 0
    total_links = 0
    drift_files: list[Path] = []
    per_file: list[tuple[Path, int]] = []

    for path in iter_target_files():
        original = path.read_text(encoding="utf-8")
        new_text, count, _pairs = process_file(
            path,
            terms,
            min_occurrences=args.min_occurrences,
            demote_below_threshold=args.demote_below_threshold,
        )
        if new_text != original:
            drift_files.append(path)
            total_files += 1
            total_links += count
            per_file.append((path, count))
            if not args.check and not args.dry_run:
                path.write_text(new_text, encoding="utf-8")
                if args.verbose:
                    print(f"  {path.relative_to(ROOT)}: +{count}")

    if args.report:
        report_path = Path(args.report)
        if not report_path.is_absolute():
            report_path = ROOT / report_path
        lines_out = [
            "# Glossary threshold dry-run report",
            "",
            f"- min-occurrences: `{args.min_occurrences}`",
            f"- demote-below-threshold: `{args.demote_below_threshold}`",
            f"- dry-run: `{args.dry_run}`",
            f"- files that would change: **{total_files}**",
            f"- links that would be injected: **{total_links}**",
            "",
            "## Per-file injection counts",
            "",
        ]
        for p, n in sorted(per_file, key=lambda x: (-x[1], x[0].as_posix())):
            lines_out.append(f"- `{p.relative_to(ROOT).as_posix()}`: +{n}")
        if not per_file:
            lines_out.append("- (none)")
        lines_out.append("")
        report_path.write_text("\n".join(lines_out), encoding="utf-8")
        print(f"report written: {report_path.relative_to(ROOT)}")

    if args.check:
        if drift_files:
            for p in drift_files:
                print(f"drift: {p.relative_to(ROOT)}", file=sys.stderr)
            print(
                f"\n{len(drift_files)} file(s) would change "
                f"({total_links} link(s) would be injected). "
                f"Run `python3 meta/scripts/inject_glossary_links.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    if args.dry_run:
        print(
            f"glossary inject (dry-run, min-occurrences={args.min_occurrences}): "
            f"{total_files} file(s) would change, "
            f"{total_links} link(s) would be injected."
        )
        return 0

    print(
        f"glossary inject: updated {total_files} file(s), "
        f"injected {total_links} link(s) total."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
